mdapioutput/objects/MedicineTrail__c.object
<CustomObject>
    <label>MedicineTrail</label>
    <nameField>
        <label>MedicineTrails Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MedicineTrails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Medicine__c</fullName>
        <label>Medicine</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trailstatus__c</fullName>
        <label>Trailstatus</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trailphase__c</fullName>
        <label>Trailphase</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/medicinetrails.cls
global with sharing class medicinetrails {
    public String objectName {get;set;}
    @RemoteAction
    global static List<MedicineTrail__c>  getRecords(String objectName){
        List<MedicineTrail__c> trailsData = new List<MedicineTrail__c>();
        trailsData = Database.query('SELECT Name, Medicine__c, Trailphase__c, Trailstatus__c  FROM MedicineTrail__c WHERE Medicine__c LIKE \'%' + objectName + '%\'');
        return trailsData;
    }
}